<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2026 Diffblue Limited

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.diffblue</groupId>
  <artifactId>diffblue-sonar</artifactId>
  <version>${revision}</version>
  <packaging>pom</packaging>

  <modules>
    <module>core</module>
    <module>sonar-plugin</module>
    <module>integration-tests</module>
  </modules>

  <properties>
    <revision>1.0.0</revision>
    <!-- required by sonarqube 9.4.0.54424 -->
    <java.version>11</java.version>
    <maven.spotless.plugin.version>2.44.3</maven.spotless.plugin.version>
    <sonar.api.version>9.4.0.54424</sonar.api.version>
    <!-- used by spotless -->
    <google.java.format.version>1.17.0</google.java.format.version>
    <gpg.plugin.version>3.2.1</gpg.plugin.version>
    <flatten.plugin.version>1.6.0</flatten.plugin.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.sonarsource.sonarqube</groupId>
        <artifactId>sonar-plugin-api</artifactId>
        <version>9.4.0.54424</version>
        <scope>provided</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>com.diffplug.spotless</groupId>
          <artifactId>spotless-maven-plugin</artifactId>
          <version>${maven.spotless.plugin.version}</version>
          <configuration>
            <java>
              <includes>
                <include>**/*.java</include>
              </includes>
              <licenseHeader>
                <file>license-java.txt</file>
                <delimiter>package |import |public class</delimiter>
              </licenseHeader>
              <googleJavaFormat>
                <version>${google.java.format.version}</version>
                <style>GOOGLE</style>
              </googleJavaFormat>
            </java>
            <pom>
              <includes>
                <include>pom.xml</include>
              </includes>
              <licenseHeader>
                <file>license-pom.txt</file>
                <delimiter>&lt;project</delimiter>
              </licenseHeader>
              <sortPom></sortPom>
            </pom>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <version>${flatten.plugin.version}</version>
        <configuration>
          <updatePomFile>true</updatePomFile>
          <flattenMode>resolveCiFriendliesOnly</flattenMode>
        </configuration>
        <executions>
          <execution>
            <id>flatten</id>
            <goals>
              <goal>flatten</goal>
            </goals>
            <phase>process-resources</phase>
          </execution>
          <execution>
            <id>flatten.clean</id>
            <goals>
              <goal>clean</goal>
            </goals>
            <phase>clean</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>sign</id>
      <activation>
        <activeByDefault>false</activeByDefault>
      </activation>
      <properties>
        <gpg.keyname>${env.GPG_ID}</gpg.keyname>
      </properties>
      <build>
        <plugins>
          <!-- GPG Plugin for signing artifacts -->
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-gpg-plugin</artifactId>
            <version>${gpg.plugin.version}</version>
            <executions>
              <execution>
                <id>sign-artifacts</id>
                <goals>
                  <goal>sign</goal>
                </goals>
                <phase>verify</phase>
                <configuration>
                  <useAgent>true</useAgent>
                  <gpgArguments>
                    <arg>--batch</arg>
                    <arg>--pinentry-mode</arg>
                    <arg>loopback</arg>
                  </gpgArguments>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
