<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2026 Diffblue Limited

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.diffblue</groupId>
    <artifactId>diffblue-sonar</artifactId>
    <version>${revision}</version>
  </parent>

  <artifactId>diffblue-sonar-plugin</artifactId>

  <packaging>sonar-plugin</packaging>
  <name>diffblue-sonar-plugin</name>

  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <sonar.version>9.4.0.54424</sonar.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.diffblue</groupId>
      <artifactId>core</artifactId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
      <groupId>org.sonarsource.sonarqube</groupId>
      <artifactId>sonar-plugin-api</artifactId>
      <version>${sonar.version}</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.sonarsource.sonarqube</groupId>
      <artifactId>sonar-plugin-api-impl</artifactId>
      <version>${sonar.version}</version>
      <scope>test</scope>
    </dependency>

    <!-- Source: https://mvnrepository.com/artifact/org.sonarsource.api.plugin/sonar-plugin-api-test-fixtures -->
    <dependency>
      <groupId>org.sonarsource.api.plugin</groupId>
      <artifactId>sonar-plugin-api-test-fixtures</artifactId>
      <version>13.4.3.4290</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.8.1</version>
      <scope>test</scope>
    </dependency>

    <!-- Source: https://mvnrepository.com/artifact/org.assertj/assertj-core -->
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <version>3.27.6</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <version>5.12.0</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-junit-jupiter</artifactId>
      <version>5.12.0</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.sonarsource.sonar-packaging-maven-plugin</groupId>
        <artifactId>sonar-packaging-maven-plugin</artifactId>
        <version>1.24.0.2621</version>
        <extensions>true</extensions>
        <configuration>
          <!-- MUST match your actual Plugin implementation class -->
          <pluginClass>com.diffblue.sonar.DiffbluePlugin</pluginClass>

          <!-- This becomes Plugin-Key in MANIFEST.MF -->
          <pluginKey>diffbluecoverage</pluginKey>

          <!-- Display name in UI -->
          <pluginName>Diffblue Coverage</pluginName>

          <pluginOrganizationName>Diffblue Limited</pluginOrganizationName>
          <pluginOrganizationUrl>https://www.diffblue.com/</pluginOrganizationUrl>

          <!-- Minimum SQ version you target -->
          <!--                    <sonarQubeMinVersion>9.4</sonarQubeMinVersion>-->

          <pluginDescription>Imports and visualises code coverage from Diffblue-generated tests in SonarQube.</pluginDescription>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.14.0</version>
        <configuration>
          <release>17</release>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
